name: Update Helm Charts

on: 
  push:
    branches:
      - main  # Specify the branches you want this workflow to run on push

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        # Ensure Python is installed (if not already available on the runner)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          sudo apt-get install jq -y
          sudo apt-get install yq -y

      - name: Generate updatecli.yaml
        run: |
          output=$(python3 Python-Script/main.py)
          echo "$output" 

      - name: Print updatecli.yaml file
        run: |
          cat updatecli.yaml          

      - name: Install updatecli
        run: |
          curl -LO https://github.com/updatecli/updatecli/releases/download/v0.80.0/updatecli_Linux_x86_64.tar.gz
          tar -zxvf updatecli_Linux_x86_64.tar.gz
          mv updatecli /usr/local/bin

      - name: check update cli version
        run: |
          updatecli version
          pwd
          cat Templates/EKS/inputs.tf  

      - name: Run updatecli
        run: updatecli apply --config .github/pdatecli.yml          

      - name: cat update cli version
        run: |
          cat Templates/EKS/inputs.tf   
