name: Run Python code

on: 
  push:
    branches:
      - main  # Specify the branches you want this workflow to run on push

jobs:
  RunPythonScript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - program: Install Python
        # Ensure Python is installed (if not already available on the runner)
        run: |
          apt-get update -y
          apt-get install python3 -y
          apt-get install jq -y
          apt-get update -y
          pip install pyyaml 
          python3 Python-Practices/retrive_data.py